# Actuator Endpunkte
management:
  endpoints:
    enabled-by-default: false
  #    web:
  #      exposure:
  #        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  server:
    port: 8079

logging:
  level:
    org:
      springframework: INFO

# Port für die Servlets
server:
  port: 8080


camel:
  component:
    servlet:
      # Basepath für Servlet-Endpunkt:
      # https://camel.apache.org/components/3.7.x/servlet-component.html#_usage_with_spring_boot
      mapping.contextpath: /*
  springboot:
    tracing: false
    main-run-controller: true
